# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Power Bill Extractor

theme:
  name: material
  icon:
    logo: material/power-plug-outline
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings

copyright: Copyright &copy; 2022 Jason Hutson